In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
test = np.array([{1,2},{3,4}])
print(test)
test

[{1, 2} {3, 4}]


array([{1, 2}, {3, 4}], dtype=object)

In [12]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a = np.array([[1,5],[4,-2]])
a

array([[ 1,  5],
       [ 4, -2]])

In [18]:
b = np.array([[2,-1],[7,6]])
b

array([[ 2, -1],
       [ 7,  6]])

In [20]:
a + b

array([[ 3,  4],
       [11,  4]])

In [21]:
a-b

array([[-1,  6],
       [-3, -8]])

In [22]:
np.dot(a,b)

array([[ 37,  29],
       [ -6, -16]])

In [3]:
A=np.array([[1,5,-2],[4,0,-3],[-8,2,6]])
A

array([[ 1,  5, -2],
       [ 4,  0, -3],
       [-8,  2,  6]])

In [2]:
import numpy as np

In [4]:
A.sum()

5

In [5]:
A.max()

6

In [6]:
A.min()

-8

In [7]:
np.average(A)

0.5555555555555556

In [8]:
np.median(A)

1.0

In [10]:
np.var(A)

17.358024691358025

In [11]:
np.std(A)

4.166296279833928

In [12]:
A=np.array([[1,5],[4,-2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [13]:
np.linalg.det(A)

-22.000000000000004

In [15]:
A_inv=np.linalg.inv(A)

In [16]:
np.dot(A,A_inv)

array([[ 1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00]])